notifications:
  webhooks:
    - https://webhook.commit-email.info/

sudo: required

services:
  - docker

install:
  - docker build -t red-data-tools/red-arrow-pycall .

script:
  - docker run red-data-tools/red-arrow-pycall /bin/sh -c "bundle exec rake"
